import { Router } from 'express';
import type { ProductsController } from './products-controller.js';

export const createProductsRouter = (controller: ProductsController): Router => {
  const router = Router();

  router.get('/', controller.search);
  router.post('/', controller.create);
  router.get('/first', controller.getFirstActive);
  router.get('/:productId/previous', controller.getPrevious);
  router.get('/:productId/next', controller.getNext);
  router.get('/:productId/actions/warehouses', controller.panel('warehouses'));
  router.get('/:productId/actions/color-size-registration', controller.panel('color-size-registration'));
  router.get('/:productId/actions/block-status', controller.panel('block-status'));
  router.patch('/:productId/actions/block-status', controller.setBlockStatus);
  router.get('/:productId/actions/classifications', controller.panel('classifications'));
  router.get('/:productId/actions/extended-description', controller.panel('extended-description'));
  router.get('/:productId/actions/discounts/customers', controller.panel('customer-discounts'));
  router.get('/:productId/actions/discounts/suppliers', controller.panel('supplier-discounts'));
  router.get('/:productId/actions/other-data', controller.panel('other-data'));
  router.get('/:productId/actions/specifications', controller.panel('specifications'));
  router.get('/:productId/actions/photo', controller.panel('photo'));
  router.get('/:productId/actions/ct-inventory', controller.panel('ct-inventory'));
  router.get('/:productId/actions/prices', controller.panel('prices'));
  router.get('/:productId/actions/skus', controller.panel('skus'));
  router.get('/:productId/actions/prepacks', controller.panel('prepacks'));
  router.get('/:productId/purchases-production/alternates', controller.panel('alternates'));
  router.get('/:productId/purchases-production/components', controller.panel('components'));
  router.get('/:productId/purchases-production/quality-specifications', controller.panel('quality-specifications'));
  router.get('/:productId/purchases-production/implosion', controller.panel('implosion'));
  router.get('/:productId/purchases-production/lots', controller.panel('lots'));
  router.get('/:productId/purchases-production/inventory-layers', controller.panel('inventory-layers'));
  router.get('/:productId/queries/ledger', controller.panel('ledger'));
  router.get('/:productId/queries/customer-orders', controller.panel('customer-orders'));
  router.get('/:productId/queries/customer-orders/star', controller.panel('customer-orders-star'));
  router.get('/:productId/queries/customer-orders/ct', controller.panel('customer-orders-ct'));
  router.get('/:productId/queries/customer-quotes', controller.panel('customer-quotes'));
  router.get('/:productId/queries/customer-sales', controller.panel('customer-sales'));
  router.get('/:productId/queries/customer-sales/star', controller.panel('customer-sales-star'));
  router.get('/:productId/queries/customer-sales/ct', controller.panel('customer-sales-ct'));
  router.get('/:productId/queries/customer-sales/detail', controller.panel('customer-sales-detail'));
  router.get('/:productId/queries/sales/by-branch', controller.panel('sales-by-branch'));
  router.get('/:productId/queries/sales/annual', controller.panel('annual-sales'));
  router.get('/:productId/queries/sales/annual-summary', controller.panel('annual-sales-summary'));
  router.get('/:productId/queries/supplier-orders', controller.panel('supplier-orders'));
  router.get('/:productId/queries/supplier-orders/ct', controller.panel('supplier-orders-ct'));
  router.get('/:productId/queries/supplier-quotes', controller.panel('supplier-quotes'));
  router.get('/:productId/queries/supplier-purchases', controller.panel('supplier-purchases'));
  router.get('/:productId/queries/supplier-purchases/dt', controller.panel('supplier-purchases-dt'));
  router.get('/:productId/queries/supplier-purchases/detail', controller.panel('supplier-purchases-detail'));
  router.get('/:productId/queries/purchases/annual', controller.panel('annual-purchases'));
  router.get('/:productId/queries/purchases/annual-summary', controller.panel('annual-purchases-summary'));
  router.get('/:productId/queries/pieces', controller.panel('pieces'));
  router.get('/:productId/queries/pieces/fulfilled', controller.panel('fulfilled-pieces'));
  router.get('/:productId/queries/work-in-progress', controller.panel('work-in-progress'));
  router.get('/:productId/queries/work-in-progress/ct', controller.panel('work-in-progress-ct'));
  router.get('/:productId/queries/edi', controller.panel('edi'));
  router.get('/:productId/queries/pending-enablements', controller.panel('pending-enablements'));
  router.get('/:productId/queries/documents', controller.panel('documents'));
  router.get('/:productId', controller.getById);
  router.patch('/:productId', controller.update);
  router.delete('/:productId', controller.delete);

  return router;
};
