import { legacyMysqlPool } from '../src/shared/infrastructure/database/legacy-mysql-pool.js';

const [headers] = await legacyMysqlPool.query(`
  SELECT PESEQ, PENUM, PENUMELLOS, PESPEDIDO, PESTATUS,
    PEFECHA, PEDESDE, PEVENCE, PEDEPTO, PEALMACEN, PESUCURSAL,
    PEPORCIVA, PEBRUTO, PEDESC, PEIEPES, PEFLETE, PESEGURO,
    PEOTRO, PEIVA, PECANT, PEPAR1, PEPAR2, PEPAR3, PEPAR4,
    PEPAR5, PEPAR6, PEPAR7, PEPAR8, PEPAR9,
    FPRV.PRVSEQ, PRVCOD, PRVNOM
  FROM FPENC
  LEFT JOIN FPRV ON FPENC.PRVSEQ = FPRV.PRVSEQ
  WHERE PESPEDIDO IN (2, 5)
  ORDER BY PENUM DESC
  LIMIT 2
`);

const [lines] = await legacyMysqlPool.query(`
  SELECT FPLIN.PLSEQ, FPLIN.ISEQ, ICOD, IDESCR, PLCANT, PLSURT,
    PLASIGNADO, PLPRECI, PLDESC, PLUNIDAD, PLFACTOR, PLCLASE,
    PLMONEDA, PLSUC, PLASIGNPZAS, ICODPRV, ICONFIRMADO
  FROM FPLIN
  LEFT JOIN FINV ON FPLIN.ISEQ = FINV.ISEQ
  WHERE FPLIN.PESEQ = (
    SELECT PESEQ FROM FPENC
    WHERE PESPEDIDO IN (2, 5)
    ORDER BY PENUM DESC LIMIT 1
  )
  ORDER BY PLSEQ
  LIMIT 3
`);

console.log(JSON.stringify({ headers, lines }, null, 2));
await legacyMysqlPool.end();
