import { legacyMysqlPool } from '../src/shared/infrastructure/database/legacy-mysql-pool.js';

const [policies] = await legacyMysqlPool.query(`
  SELECT
    FPOLIZA.POSEQ, PONUM, POFECHA, PODESCR, POBENEF, POCHEQUE,
    POAPLICADA, POFAMILIA, POPAR1, POPAR2, POCAMBIO, POCIA, POORIGEN,
    COUNT(FBANMOV.BASEQ) AS MOVIMIENTOS
  FROM FPOLIZA
  LEFT JOIN FBANMOV ON FPOLIZA.POSEQ = FBANMOV.POSEQ
  WHERE POEST = 0 AND POCIA = 1
  GROUP BY FPOLIZA.POSEQ
  HAVING COUNT(FBANMOV.BASEQ) > 0
  ORDER BY FPOLIZA.POSEQ DESC
  LIMIT 10
`);

const [sample] = await legacyMysqlPool.query(`
  SELECT
    FPOLIZA.POSEQ, PONUM, PODESCR, POFECHA, POAPLICADA, POBENEF,
    POCHEQUE, POLETRA, POUSR, POEST, POREPORTE, POFAMILIA, POAUDIT,
    POPOSTFECHA, POPAR1, POPAR2, POCAMBIO, POFUSA, POCIA, POORIGEN
  FROM FPOLIZA
  WHERE FPOLIZA.POSEQ = 318185
  LIMIT 1
`);

const [movements] = await legacyMysqlPool.query(`
  SELECT
    FBANMOV.BASEQ, FBANMOV.BSEQ, BCOD, BNOMBRE, BAIMPOR, BAIMPORNEG,
    BABENEF, BATIPOC, BACENCOS, BAOK, BTIPO
  FROM FBANMOV
  LEFT JOIN FBENC ON FBANMOV.BSEQ = FBENC.BSEQ
  WHERE FBANMOV.POSEQ = 318185
  ORDER BY FBANMOV.BASEQ
`);

const [comments] = await legacyMysqlPool.query(`
  SELECT COMSEQ, COMSEQFACT, COML1, COML2, COML3, COML4, COMDES
  FROM FCOMENT
  WHERE COMSEQFACT IN (318185, 10318185, 20318185, 30318185)
  ORDER BY COMSEQ
`);

console.log(JSON.stringify({ policies, sample, movements, comments }, null, 2));
await legacyMysqlPool.end();
